Content:

  Global:

    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:

  Busquedas:
    
    busqueda:
      model: busqueda
      page: true
      components:
        form:
        list:
        show:
    respuesta_busqueda:
      model: respuestab
      page:  true
      components:
        listByBusqueda:
        show:
  Preguntas:
    
    pregunta:
      model: pregunta
      page: true
      components:
        form:
        list:
        show:

    respuesta:
      model: respuesta
      page: true
      components:
        listByPregunta:
        show:

  Recursos:
    recurso:
      model: Recurso
      page: true
      components:
        list:
        show:
        form:
    tesis:
      page: true
      components:
        list:
        show:
        form:
    monografia:
      page: true
      components:
        list:
        show:
        form:
    articulo:
      page: true
      components:
        list:
        show:
        form:
    BibliotecaPersonal:
      page: true
      components:
        list:
        show:
        form:
    DocumentoLegal:
      page: true
      components:
        list:
        show:
        form:
    patente:
      page: true
      components:
        list:
        show:
        form:
    presentacion:
      page: true
      components:
        list:
        show:
        form:
    autor:
      page: true
      components:
        form:
        list:
  Prestamos:
    prestamo:
      page: true
      components:
        form:
        list:
    SolicitudPrestamo:
      page: true
      components:
        form:
        list: