Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:

  Busquedas:
    
    busqueda:
      model: busqueda
      page: true
      components:
        form:
        list:
        show:
    respuesta_busqueda:
      model: respuestab
      page:  true
      components:
        listByBusqueda:
        show:
  Recursos:
    tesis:
      model: tesis
      page: true
      components:
        form:
        list:
        show:
        formUpload:

    monografia:
      model: monografia
      page: true
      components:
        form:
        list:
        show:
    recurso:
      model: recurso
      components:
        list:
        form:
        show: