Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:

  Busquedas:
    
    busqueda:
      model: busqueda
      page: true
      components:
        form: