generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Patente
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: patente
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        autors_list:
          label: Autors
        tematicas_list:
          label: Tematicas
        dm_users_list:
          label: Users
        is_active:
          label: Active
      list:
        display:
          - '=id'
          - '=titulo'
          - anno
          - idioma
          - prestado
          - is_active
          - formato_duro
          - palabras_claves
          - pais
          - institucion
          - total_paginas
          - num_internacional
          - slide_id
          - tematicas_list
          - created_at
          - updated_at
          - created_by
          - updated_by
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - id
          - prestado
          - is_active
          - formato_duro
          - titulo
          - anno
          - idioma
          - palabras_claves
          - pais
          - institucion
          - num_internacional
          - created_at
          - updated_at
          - created_by
          - updated_by
      form:
        display:
          NONE: [prestado, is_active, formato_duro, tags]
          Slide: [slide_id_form, slide_id_view]
          Datos: [titulo, anno, resumen, idioma, palabras_claves, pais, institucion, total_paginas, num_internacional, tematicas_list]
        class: PatenteAdminForm
        fields: {  }
      edit: ~
      new: ~
