generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: monografia
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: monografia
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        autor_list:
          label: Autor
        tematica_list:
          label: Tematicas
        dm_users_list:
          label: Users
        is_active:
          label: Active
      list:
        display:
          - '=id'
          - '=titulo'
          - anno
          - idioma
          - prestado
          - is_active
          - formato_duro
          - palabras_claves
          - ciudad_pub
          - editorial
          - total_paginas
          - isbn
          - num_inventario
          - slide_id
          - tematicas_list
          - autors_list
          - created_at
          - updated_at
          - created_by
          - updated_by
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - prestado
          - is_active
          - formato_duro
          - titulo
          - anno
          - idioma
          - palabras_claves
          - ciudad_pub
          - editorial
          - isbn
          - num_inventario
          - created_at
          - updated_at
          - created_by
          - updated_by
      form:
        display:
          NONE: [prestado, is_active, formato_duro]
          Pdf: [slide_id_form, slide_id_view]
          Recurso: [titulo, anno, resumen, idioma, isbn, num_inventario, editorial, palabras_claves, total_paginas, tematicas_list, autors_list]
        class: monografiaAdminForm
        fields: 
          anno: {label: A&ntildeo de publicaci&oacuten }
      edit: ~
      new: ~
