<?php

/**
 * Autor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bibliocnic
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Autor extends BaseAutor
{
public function __toString()
  {
    $nombre = $this->nombre;
	$apellidos = $this->apellidos;
	$array = array($apellidos, $nombre);
	$comas = implode(", ", $array);
	return $comas;
  }

}