generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: pregunta
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: pregunta
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=id'
          - dm_user_id
          - titulo
          - mensaje
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - dm_user_id
          - titulo
          - mensaje
          - created_at
          - updated_at
      form:
        display:
          NONE: [dm_user_id]
          Mensaje: [mensaje]
          Others: [titulo]
        class: preguntaAdminForm
        fields: {  }
      edit: ~
      new: ~
