generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: bibliotecapersonal
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: biblioteca_personal
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        autors_list:
          label: Autors
        tematicas_list:
          label: Tematicas
        dm_users_list:
          label: Users
        is_active:
          label: Active
      list:
        display:
          - '=id'
          - '=titulo'
          - anno
          - idioma
          - aprobado
          - is_active
          - formato_duro
          - palabras_claves
          - cant_registros
          - fecha_inicial
          - slide_id
          - tematicas_list
          - created_at
          - updated_at
          - created_by
          - updated_by
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - id
          - aprobado
          - is_active
          - formato_duro
          - titulo
          - anno
          - idioma
          - palabras_claves
          - fecha_inicial
          - created_at
          - updated_at
          - created_by
          - updated_by 
      form:
        display:
          NONE: [aprobado, is_active, formato_duro]
          PDF: [slide_id_form, slide_id_view]
          Others: [titulo, anno, resumen, idioma, palabras_claves, cant_registros, fecha_inicial, tematicas_list]
        class: bibliotecapersonalAdminForm
        fields: {  }
      edit: ~
      new: ~
