generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Tesis
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: tesis
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        autors_list:
          label: Autors
        tematicas_list:
          label: Tematicas
        dm_users_list:
          label: Users
        is_active:
          label: Active
      list:
        display:
          - '=id'
          - '=titulo'
          - anno
          - idioma
          - prestado
          - is_active
          - formato_duro
          - palabras_claves
          - departamento
          - total_paginas
          - ciudad
          - institucion
          - tutors_list
          - tipo
          - tutor
          - slide_id
          - tematicas_list
          - created_at
          - updated_at
          - created_by
          - updated_by
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - id
          - aprobado
          - is_active
          - formato_duro
          - titulo
          - anno
          - idioma
          - palabras_claves
          - departamento
          - ciudad
          - institucion
          - tutor
          - tipo
          - created_at
          - updated_at
          - created_by
          - updated_by 
      form:
        display:
          NONE: [aprobado, is_active, formato_duro]
          PDF: [slide_id_form, slide_id_view]
          Datos: [titulo, anno, resumen, idioma, palabras_claves, departamento, ciudad, institucion, total_paginas, tutor, tipo, tematicas_list]
        class: TesisAdminForm
        fields:
          tutor: { help: 'Por favor separe los nombres de los tutores por comas' }
      edit: ~
      new: ~
