default:
  
  http_metas:
    content-type: text/html

  stylesheets:
    - layout
    - homepage
    - forms
    - navi
    - tables
    - main
    - markdown

  javascripts:

  has_layout:     true
  layout:         layout