generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Recurso
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: recurso
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        autors_list:
          label: Autors
        tematicas_list:
          label: Tematicas
        dm_users_list:
          label: Users
        is_active:
          label: Active
      list:
        display:
          - '=id'
          - slide_id
          - created_by
          - updated_by
          - autors_list
          - tematicas_list
          - dm_users_list
          - titulo
          - anno
          - resumen
          - idioma
          - prestado
          - is_active
          - formato_duro
          - palabras_claves
          - type
          - pais
          - institucion
          - total_paginas
          - num_internacional
          - organismo
          - tipo_dc
          - cant_registros
          - fecha_inicial
          - ciudad_pub
          - editorial
          - isbn
          - volumen
          - num_revista
          - pagina_inicial
          - pagina_final
          - issn
          - num_diapositivas
          - departamento
          - ciudad
          - tutor
          - tipo
          - created_at
          - updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - id
          - aprobado
          - is_active
          - formato_duro
          - titulo
          - anno
          - resumen
          - idioma
          - palabras_claves
          - slide_id
          - type
          - pais
          - institucion
          - total_paginas
          - num_internacional
          - organismo
          - tipo_dc
          - cant_registros
          - fecha_inicial
          - fecha_final
          - ciudad_pub
          - editorial
          - isbn
          - volumen
          - num_revista
          - pagina_inicial
          - issn
          - num_diapositivas
          - departamento
          - ciudad
          - tutor
          - tipo
          - created_at
          - updated_at
          - created_by
          - updated_by
      form:
        display:
          NONE: [aprobado, is_active, formato_duro]
          Slide: [slide_id_form, slide_id_view]
          Others: [titulo, anno, resumen, idioma, palabras_claves, type, pais, institucion, total_paginas, num_internacional, organismo, tipo_dc, cant_registros, fecha_inicial, ciudad_pub, editorial, isbn, volumen, num_revista, pagina_inicial, pagina_final, issn, num_diapositivas, departamento, ciudad, tutor, tipo]
        class: RecursoAdminForm
        fields: {  }
      edit: ~
      new: ~
