generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: respuesta
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: respuesta
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=id'
          - '=pregunta_id'
          - mensaje
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - pregunta_id
          - created_at
          - updated_at
      form:
        display:
          Pregunta: [pregunta_id]
          NONE: [mensaje]
        class: respuestaAdminForm
        fields: {  }
      edit: ~
      new: ~
