Recurso:
  actAs:
    Timestampable:
    DmVersionable:
    DmSortable:
    DmBlameable:
#    DmSluggable:
#    DmSearchable:
#      fields: [titulo, resumen]
 #   DmTaggable:
  columns:
    id: {type: integer, autoincrement: true, primary: true}
    titulo: {type: string(40), notnull: true}
    anno: {type: string(4)}
    resumen: {type: string(255)}
    idioma: {type: string(24)}
    aprobado: {type: boolean, default: false}
    is_active: {type: boolean, default: false}
    fichero: {type: string(255), notnull: false}
    formato_duro: {type: boolean, default: false}
  relations:
    Autor:
      class: Autor
      refClass: RecursoAutor
      foreignAlias: Recursos
      onDelete: CASCADE
    Tematica:
      class: Tematica
      refClass: RecursoTematica
      foreignAlias: Recursos
      onDelete: RESTRICT
    DmUser:
      class: DmUser
      refClass: SolicitudPrestamo
      foreignAlias: Recursos
      onDelete: CASCADE
    DmUser:
      class: DmUser
      refClass: Descarga
      foreignAlias: Recursos
    DmUser:
      class: DmUser
      foreignAlias: Recursos
      refClass: Prestamo
    

Autor:
  actAs:
#    DmSluggable:
#    DmSearchable:
#      file: [nombre, apellidos]
  columns:
    id: {type: integer, autoincrement: true, primary: true}
    nombre: {type: string(32), notnull: true}
    apellidos: {type: string(40), notnull: true}

RecursoAutor:
  columns:
    autor_id: {type: integer, primary: true}
    recurso_id: {type: integer, primary: true}
  relations:
    Autor:
      foreignAlias: RecursoAutors
    Recurso:
      foreignAlias: RecursoAutors

RecursoTematica:
  columns:
    tematica_id: {type: integer, primary: true}
    recurso_id: {type: integer, primary: true}
  relations:
    Tematica:
      foreignAlias: RecursoTematicas
    Recurso:
      foreignAlias: RecursoTematicas

Tematica:
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    nombre: {type: string(32), notnull: true}

DmUser:
  actAs:
    Timestampable:
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    titulo: {type: enum, values: [9no, 12, Lic, Ing, MsC, Dr]}
    nombre: {type: string(32), notnull: true}
    apellidos: {type: string(40), notnull: true}
    email: {type: string(32), notnull: true, unique: true}
    foto_id: {type: integer, notnull: false}
    is_active: {type: boolean, default: true}
    penalizado: {type: boolean, default: false}
  relations:
    Image:
      class: DmMedia
      local: foto_id
      onDelete: RESTRICT

SolicitudPrestamo:
  actAs:
    Timestampable:
  columns:
    user_id: {type: integer, primary: true,}
    recurso_id: {type: integer, primary: true,}
  relations:
    DmUser:
      foreignAlias: SolicitudPrestamos
    Recurso:
      foreignAlias: SolicitudPrestamos
      onDelete: CASCADE

Descarga:
  actAs:
    Timestampable:
  columns:
    recurso_id: {type: integer, primary: true}
    user_id: {type: integer, primary: true}
  relations:
    DmUser:
      local: user_id
      foreignAlias: Descargas
      onDelete: RESTRICT
    Recurso:
      foreignAlias: Descargas
      onDelete: RESTRICT

Prestamo:
  actAs:
    Timestampable:
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    user_id: {type: integer, primary: true}
    recurso_id: {type: integer, primary: true}
    fecha_devolucion: {type: timestamp, notnull: true}
    prorroga: {type: boolean, default: false}
  relations:
    DmUser:
      foreignAlias: Prestamos
      onDelete: CASCADE
    Recurso:
      foreignAlias: Prestamos
      onDelete: CASCADE
Patente:
  inheritance:
    extends: Recurso
    type: column_aggregation
    keyField: type
    keyValue: Patente
  columns:
    pais: {type: string(32)}
    institucion: {type: string(40)}
    total_paginas: {type: integer(4)}
    num_internacional: {type: string(32)}

DocumentoLegal:
  inheritance:
    extends: Recurso
    type: column_aggregation
    keyField: type
    keyValue: DocumentoLegal
  columns:
    organismo: {type: string(40)}
    total_paginas: {type: integer(4)}
    tipo_dc: {type: enum, values: [Procedimiento, Ley]}

BibliotecaPersonal:
  inheritance:
    extends: Recurso
    type: column_aggregation
    keyField: type
    keyValue: BibliotecaPersonal
  columns:
    cant_registros: {type: integer(4)}
    fecha_inicial: {type: timestamp}
    fecha_final: {type: timestamp}

Monografia:
  inheritance:
    extends: Recurso
    type: column_aggregation
    keyField: type
    keyValue: Monografia
  columns:
    ciudad_pub: {type: string(32)}
    editorial: {type: string(32)}
    total_paginas: {type: integer(4)}
    isbn: {type: string(16)}

Articulo:
  inheritance:
    extends: Recurso
    type: column_aggregation
    keyField: type
    keyValue: Articulo
  columns:
    volumen: {type: string(16)}
    num_revista: {type: string(16)}
    pagina_inicial: {type: integer(3)}
    pagina_final: {type: integer(3)}
    issn: {type: string(16)}

Presentacion:
  inheritance:
    extends: Recurso
    type: column_aggregation
    keyField: type
    keyValue: Presentacion
  columns:
    num_diapositivas: {type: integer(3)}

Tesis:
  inheritance:
    extends: Recurso
    type: column_aggregation
    keyField: type
    keyValue: Tesis
  columns:
    departamento: {type: string(32)}
    ciudad: {type: string(32)}
    institucion: {type: string(32)}
    total_paginas: {type: integer(4)}
    tutor: {type: string(128)}
    tipo: {type: enum, values: [Pregrado, Maestria, Doctorado]}

Busqueda:
  actAs:
    Timestampable:
#    DmTaggable:
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    user_id: {type: integer}
    titulo: {type: string(128)}
    mensaje: {type: clob, extra: markdown}
    is_active: {type: boolean, default: true}
  relations:
    DmUser:
      local: user_id
      foreignAlias: Busquedas
      onDelete: RESTRICT

Respuestab:
  actAs:
    Timestampable:
  columns:
    id: {type: integer, primary: true}
    mensaje: {type: clob, extra: markdown}
    busqueda_id: {type: integer}
    uri: {type: string}
  relations:
    Busqueda:
      foreignAlias: Respuestabs
      onDelete: CASCADE

Respuesta:
  actAs:
    Timestampable:
    DmBlameable:
  columns:
    id: {type: integer, primary: true}
    mensaje: {type: clob, extra: markdown}
    pregunta_id: {type: integer}
  relations:
    Pregunta:
      foreignAlias: Respuestas
      onDelete: CASCADE

RespuestaSolicitud:
  inheritance:
    extends: Respuesta
    type: simple
  columns:
    solicitud_id: {type: integer}
    recurso_id: {type: integer}
  relations:
    Solicitud:
      local: solicitud_id
      foreign: id
      onDelete: CASCADE
    Recurso:
      local: recurso_id
      foreign: id
      onDelete: CASCADE

Pregunta:
  actAs:
    Timestampable:
  columns:
    id: {type: integer, primary: true}
    user_id: {type: integer, notnull: true}
    titulo: {type: string(128)}
    mensaje: {type: clob, extra: markdown}
  relations:
    DmUser:
      local: user_id
      foreignAlias: Preguntas

Diseminacion:
  columns:
    user_id: {type: integer, primary: true}
    tematica_id: {type: integer, primary: true}
  relations:
    DmUser:
      local: user_id
      foreignAlias: Diseminacions
    Tematica:
      foreignAlias: Diseminacions
      onDelete: CASCADE

Prestamo:
  columns:
    id: {type: integer, primary: true}
    user_id: {type: integer, notnull: true, unique: true}
    recurso_id: {type: integer, notnull: true, unique: true}
    fecha_prestamo: {type: timestamp, notnull: true}
    fecha_devolucion: {type: timestamp, notnull: true}
    prorroga: {type: boolean, default: false}
  relations:
    DmUser:
      local: user_id
      foreignAlias: Prestamos
      onDelete: RESTRICT
    Recurso:
      foreignAlias: Prestamos
      onDelete: CASCADE

SolicitudPrestamo:
  actAs:
    Timestampable:
  columns:
    user_id: {type: integer, unique: true, notnull: true}
    recurso_id: {type: integer, unique: true, notnull: true}
  relations:
    DmUser:
      local: user_id
      foreignAlias: SolicitudPrestamos
    Recurso:
      foreignAlias: SolicitudPrestamos
      onDelete: CASCADE

SolicitudProrroga:
    actAs:
      Timestampable:
    columns:
      prestamo_id: {type: integer}
      id: {type: integer, primary: true, autoincrement: true}
    relations:
      Prestamo:
        foreignAlias: SolicitudProrrogas
        onDelete: CASCADE