generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Autor
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: autor
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        recursos_list:
          label: Recursos
      list:
        display:
          - '=id'
          - nombre
          - apellidos
        sort:
          - apellidos
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - nombre
          - apellidos
      form:
        display:
          Recursos: [recursos_list]
          Others: [nombre, apellidos]
        class: AutorAdminForm
        fields: {  }
      edit: ~
      new: ~
